services:
  bedrock-server:
    container_name: bedrock-server
    image: itzg/minecraft-bedrock-server
    ports:
      - "3737:19132/udp"

    environment:
      EULA: "TRUE"
      SERVER_NAME: "Bia, Bruno e Álef"
      GAMEMODE: "creative"
      DIFFICULTY: "hard"
      LEVEL_SEED: "94a107ba"

    tty: true
    stdin_open: true
    restart: unless-stopped

    volumes:
      - ./data:/data
    networks: 
      - bedrock-server

networks:
  bedrock-server:
    driver: bridge
