services:
  bedrock-server:
    container_name: bedrock-server
    image: itzg/minecraft-bedrock-server
    ports:
      - "19132:19132/udp"

    environment:
      EULA: "TRUE"
      SERVER_NAME: "Bia, Bruno e Álef"
      GAMEMODE: "survival"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "12"
      LEVEL_SEED: "424d"
      ALLOW_CHEATS: "true"

    tty: true
    stdin_open: true
    restart: always

    volumes:
      - ./data:/data
    networks:
      - bedrock-server

networks:
  bedrock-server:
    driver: bridge
